#!/usr/bin/env python3
"""Generate src/Balsoft.Hive.EInvoice/CodeLists/CodeListData.g.cs from the official EN 16931
CII validation artefact (the Schematron compiled to XSLT that ships with the KoSIT
XRechnung validator configuration).

The BR-CL-* rules of EN 16931 embed every permitted code list as a space separated
token string inside the assertion test. Extracting them from the artefact itself keeps
the library's code lists identical to what the validators check.

Usage:
    python eng/codelists/extract_codelists.py <path/to/EN16931-CII-validation.xsl> [source-label]
"""
from __future__ import annotations

import html
import pathlib
import re
import sys

# rule id -> (C# member name, description). The rule is the authority for the list.
RULES = {
    "BR-CL-01": ("InvoiceTypeCodes", "UNTDID 1001 document type codes permitted for BT-3"),
    "BR-CL-04": ("CurrencyCodes", "ISO 4217 alpha-3 currency codes (BT-5, BT-6)"),
    "BR-CL-06": ("VatDateCodes", "UNTDID 2005 VAT point date codes (BT-8)"),
    "BR-CL-07": ("ObjectIdentifierSchemes", "UNTDID 1153 reference qualifiers (BT-18-1, BT-128-1)"),
    "BR-CL-08": ("TextSubjectCodes", "UNTDID 4451 text subject qualifiers (BT-21)"),
    "BR-CL-10": ("IdentifierSchemes", "ISO 6523 ICD identifier schemes (BT-29-1, BT-46-1, BT-60-1, BT-71-1, BT-157-1)"),
    "BR-CL-11": ("RegistrationIdentifierSchemes", "ISO 6523 ICD schemes for legal registration identifiers (BT-30-1, BT-47-1, BT-61-1)"),
    "BR-CL-13": ("ItemClassificationSchemes", "UNTDID 7143 item classification schemes (BT-158-1)"),
    "BR-CL-14": ("CountryCodes", "ISO 3166-1 alpha-2 country codes (BT-40, BT-55, BT-69, BT-80, BT-159)"),
    "BR-CL-16": ("PaymentMeansCodes", "UNTDID 4461 payment means codes (BT-81)"),
    "BR-CL-17": ("VatCategoryCodes", "UNTDID 5305 VAT category codes (BT-95, BT-102, BT-118, BT-151)"),
    "BR-CL-19": ("AllowanceReasonCodes", "UNTDID 5189 allowance reason codes (BT-98, BT-140)"),
    "BR-CL-20": ("ChargeReasonCodes", "UNTDID 7161 charge reason codes (BT-105, BT-145)"),
    "BR-CL-22": ("VatExemptionReasonCodes", "CEF VATEX exemption reason codes (BT-121)"),
    "BR-CL-23": ("UnitCodes", "UN/ECE Recommendation 20 with Rec 21 extension unit codes (BT-130, BT-150)"),
    "BR-CL-24": ("MimeCodes", "MIME codes permitted for attachments (BT-125-1)"),
    "BR-CL-25": ("ElectronicAddressSchemes", "CEF EAS electronic address schemes (BT-34-1, BT-49-1)"),
}

ASSERT = re.compile(r'<svrl:failed-assert\b[^>]*?id="(BR-CL-\d+)"[^>]*>\s*<xsl:attribute name="test">(.*?)</xsl:attribute>', re.S)
LIST = re.compile(r"contains\(\s*'\s*([^']+?)\s*'")
# a few rules (BR-CL-24) are written as a chain of "@attr = 'value'" comparisons
EQUALS = re.compile(r"=\s*'([^']+)'")


def extract(xsl: str) -> dict[str, list[str]]:
    found: dict[str, list[str]] = {}
    for rule, test in ASSERT.findall(xsl):
        test = html.unescape(test)
        lists = [m.split() for m in LIST.findall(test)]
        if not lists and " or " in test:
            lists = [EQUALS.findall(test)]
        if not lists:
            continue
        longest = max(lists, key=len)
        if len(longest) > len(found.get(rule, [])):
            found[rule] = longest
    return found


def render(found: dict[str, list[str]], source: str) -> str:
    out = [
        "// <auto-generated>",
        "// Generated by eng/codelists/extract_codelists.py from the EN 16931 CII validation",
        f"// artefact ({source}). Do not edit by hand; re-run the script instead.",
        "// </auto-generated>",
        "#nullable enable",
        "namespace Balsoft.Hive.EInvoice.CodeLists;",
        "",
        "internal static class CodeListData",
        "{",
    ]
    for rule, (name, desc) in RULES.items():
        codes = found.get(rule)
        if not codes:
            raise SystemExit(f"rule {rule} ({name}) not found in the artefact")
        codes = sorted(set(codes), key=lambda c: (len(c), c)) if name == "InvoiceTypeCodes" else sorted(set(codes))
        out.append(f"    /// <summary>{desc}. Source rule: {rule}, {len(codes)} codes.</summary>")
        out.append(f"    internal static readonly string[] {name} =")
        out.append("    {")
        line = "       "
        for c in codes:
            token = f' "{c}",'
            if len(line) + len(token) > 110:
                out.append(line)
                line = "       "
            line += token
        out.append(line)
        out.append("    };")
        out.append("")
    out[-1] = "}"
    out.append("")
    return "\n".join(out)


def main() -> None:
    if len(sys.argv) < 2:
        raise SystemExit(__doc__)
    xsl = pathlib.Path(sys.argv[1]).read_text(encoding="utf-8")
    source = sys.argv[2] if len(sys.argv) > 2 else "KoSIT XRechnung validator configuration"
    found = extract(xsl)
    target = pathlib.Path(__file__).resolve().parents[2] / "src" / "Balsoft.Hive.EInvoice" / "CodeLists" / "CodeListData.g.cs"
    target.write_text(render(found, source), encoding="utf-8", newline="\n")
    for rule, (name, _) in RULES.items():
        print(f"{rule:9} {name:32} {len(found.get(rule, []))}")


if __name__ == "__main__":
    main()
